import marimo

app = marimo.App()


@app.cell
def _():
    import marimo as mo
    return (mo,)


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    # Path C --- Advanced Reinforcement Learning

    Module 3D gave you the foundations: MDPs, value functions, Bellman equations, Q-learning, policy gradients, actor-critic methods. That's enough to understand the field and solve toy problems. But between "I can implement REINFORCE on CartPole" and "I understand how AlphaZero works" lies a vast landscape of ideas that make RL actually work on hard problems.

    This guide is a roadmap through that landscape. It's not a linear lecture --- it's a set of directions you can explore in any order, depending on what interests you. Each section gives you the core idea, the key methods, and pointers to the papers and resources where you can go deep.

    > **Primary references:** [Sutton & Barto](file:///C:/Users/landa/ml-course/textbooks/Sutton-RL.pdf) remains the bible --- if you haven't finished it cover to cover, now is the time. David Silver's UCL RL course (freely available on YouTube) is the best video companion. OpenAI's [Spinning Up](https://spinningup.openai.com/) is excellent for implementation-oriented learning.
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ---

    ## 1. Model-Based RL: Learning a World Model

    Everything in Module 3D was **model-free** --- the agent learns directly from experience without ever building an explicit model of how the environment works. Model-based RL takes the opposite approach: learn a model of the environment's dynamics $\hat{p}(s', r \mid s, a)$, then use that model to plan.

    Why bother? Sample efficiency. Model-free methods need millions of environment interactions because they extract only a thin signal from each experience. A learned world model lets you simulate experience internally --- "imagination" --- extracting far more value from the same data.

    **Dyna** ([Sutton & Barto Ch 8](file:///C:/Users/landa/ml-course/textbooks/Sutton-RL.pdf)) is the simplest version: learn a model, then interleave real experience with simulated experience generated by the model. You get more training updates per real step. The idea is almost embarrassingly simple, and it works surprisingly well.

    **MuZero** (Schrittwieser et al., 2020; [arXiv:1911.08265](https://arxiv.org/abs/1911.08265)) is the apex of model-based planning. It learns a latent dynamics model --- not a model of raw observations, but of abstract states --- and combines it with Monte Carlo Tree Search. MuZero achieved superhuman performance on Atari, chess, shogi, and Go without ever being told the rules of any game. The key insight: you don't need to predict pixels; you only need to predict values, rewards, and policies.

    **Dreamer** (Hafner et al., 2020; [arXiv:1912.01603](https://arxiv.org/abs/1912.01603)) learns a world model in a latent space and then trains the policy entirely "inside the dream" --- by backpropagating through imagined trajectories. Dreamer v3 ([arXiv:2301.04104](https://arxiv.org/abs/2301.04104)) scales this to diverse domains from Atari to robotic control to Minecraft, with a single fixed set of hyperparameters.

    **The tradeoff.** Model-based methods are more sample-efficient but introduce a new failure mode: model error. If your learned model is wrong --- and it will be, especially in regions of the state space you haven't visited --- planning with it will produce bad policies. This is called **compounding model error**, and it's the central tension in model-based RL. The field spends a lot of energy on methods that are robust to imperfect models.
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ---

    ## 2. Advanced Policy Gradient Methods

    Vanilla policy gradient (REINFORCE) works in theory but is nearly useless in practice --- the variance is too high, and there's no principled way to choose a step size. Modern policy gradient methods fix both problems.

    ### Trust Region Policy Optimization (TRPO)

    The core problem: if your policy update is too large, you can catastrophically destroy a good policy. TRPO (Schulman et al., 2015; [arXiv:1502.05477](https://arxiv.org/abs/1502.05477)) solves this by constraining updates to stay within a "trust region" --- a region where the local approximation to the objective is reliable. Formally, it maximizes a surrogate objective subject to a KL-divergence constraint between the old and new policies:

    $$\max_\theta \; \mathbb{E}\left[\frac{\pi_\theta(a|s)}{\pi_{\theta_\text{old}}(a|s)} \hat{A}(s, a)\right] \quad \text{subject to} \quad \mathbb{E}\left[D_\text{KL}(\pi_{\theta_\text{old}} \| \pi_\theta)\right] \leq \delta$$

    This requires computing the Fisher information matrix, making it computationally expensive. But it comes with theoretical monotonic improvement guarantees.

    ### Proximal Policy Optimization (PPO)

    PPO (Schulman et al., 2017; [arXiv:1707.06347](https://arxiv.org/abs/1707.06347)) achieves similar stability to TRPO with a much simpler implementation. Instead of a hard KL constraint, it clips the probability ratio:

    $$L^\text{CLIP}(\theta) = \mathbb{E}\left[\min\left(r_t(\theta)\hat{A}_t, \; \text{clip}(r_t(\theta), 1-\epsilon, 1+\epsilon)\hat{A}_t\right)\right]$$

    where $r_t(\theta) = \pi_\theta(a_t|s_t) / \pi_{\theta_\text{old}}(a_t|s_t)$. The clipping prevents the ratio from moving too far from 1, which indirectly constrains the policy change. PPO is the default algorithm for most practical applications --- it's what OpenAI used for DOTA 2, and it's the starting point for RLHF.

    ### Soft Actor-Critic (SAC) and Maximum Entropy RL

    SAC (Haarnoja et al., 2018; [arXiv:1801.01290](https://arxiv.org/abs/1801.01290)) takes a fundamentally different approach: instead of just maximizing expected reward, it maximizes reward plus entropy:

    $$J(\pi) = \mathbb{E}\left[\sum_{t=0}^{\infty} \gamma^t \left(r_t + \alpha \mathcal{H}(\pi(\cdot | s_t))\right)\right]$$

    The entropy bonus $\alpha \mathcal{H}(\pi)$ encourages the policy to be as random as possible while still achieving high reward. This is the **maximum entropy RL framework**. Why is this useful?

    - **Exploration:** High-entropy policies explore more broadly, avoiding premature convergence to suboptimal deterministic strategies.
    - **Robustness:** Stochastic policies are more robust to perturbations --- they don't commit fully to a single action.
    - **Multi-modality:** When multiple strategies are equally good, max-entropy RL captures all of them rather than arbitrarily picking one.

    SAC is off-policy (uses a replay buffer) and works in continuous action spaces, making it the go-to algorithm for robotic control tasks.
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ---

    ## 3. Multi-Agent RL and Self-Play

    When multiple agents interact in a shared environment, everything gets harder. The environment is no longer stationary from any single agent's perspective --- the other agents are learning too, so the "dynamics" keep changing.

    **Cooperative settings** require agents to coordinate. Communication protocols, shared reward signals, and centralized training with decentralized execution (CTDE) are common approaches. See QMIX ([arXiv:1803.11485](https://arxiv.org/abs/1803.11485)) and MAPPO ([arXiv:2103.01955](https://arxiv.org/abs/2103.01955)).

    **Competitive settings** involve zero-sum or general-sum games. Here, **self-play** --- training an agent against copies of itself --- is the dominant paradigm. Self-play provides an automatically scaling curriculum: as the agent improves, its opponent improves too, forcing continued learning.

    **AlphaGo** (Silver et al., 2016; [arXiv:1607.02239](https://arxiv.org/abs/1607.02239)) combined supervised learning from human games with self-play RL and Monte Carlo Tree Search (MCTS). **AlphaZero** (Silver et al., 2017; [arXiv:1712.01815](https://arxiv.org/abs/1712.01815)) dropped the human data entirely --- learning chess, shogi, and Go from scratch through pure self-play. The architecture is simple: a neural network predicts both a policy (move probabilities) and a value (probability of winning) from the board position. MCTS uses these predictions to search ahead, and the search results become training targets for the network. This loop --- neural network guides search, search improves neural network --- is one of the most elegant ideas in all of AI.
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ---

    ## 4. Offline RL: Learning from Fixed Datasets

    Standard RL assumes you can interact with an environment. But what if you can't? What if you only have a fixed dataset of previously collected transitions --- perhaps from a legacy controller, human demonstrations, or logged data from a production system?

    This is **offline RL** (also called batch RL), and it's surprisingly difficult. The core problem is **distribution shift**: the policy you're learning wants to take actions that your dataset doesn't cover. When you query the Q-function for an unseen (state, action) pair, you get an unreliable estimate, and standard RL algorithms exploit these errors catastrophically --- they seek out exactly those out-of-distribution actions where the Q-function is most wrong (and most optimistic).

    **Conservative Q-Learning (CQL)** (Kumar et al., 2020; [arXiv:2006.04779](https://arxiv.org/abs/2006.04779)) addresses this by adding a regularizer that pushes down Q-values for actions not seen in the dataset, producing a conservative (pessimistic) estimate. The policy then only exploits actions it has evidence for.

    **Decision Transformers** (Chen et al., 2021; [arXiv:2106.01345](https://arxiv.org/abs/2106.01345)) reframe RL as a sequence modeling problem. Instead of learning value functions, you train a transformer to predict actions conditioned on desired future returns. At test time, you condition on a high return and let the transformer generate the corresponding actions. This completely sidesteps the bootstrapping and off-policy issues of traditional offline RL --- at the cost of losing Bellman-style reasoning about long-horizon problems.
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ---

    ## 5. Hierarchical RL

    Flat RL policies struggle with tasks that require long sequences of coordinated actions --- navigating a maze, cooking a meal, assembling furniture. **Hierarchical RL** decomposes the problem into levels of abstraction.

    The **options framework** ([Sutton & Barto S17.1](file:///C:/Users/landa/ml-course/textbooks/Sutton-RL.pdf)) formalizes this: an option is a temporally extended action consisting of a policy, an initiation set, and a termination condition. A higher-level policy chooses which option to invoke, and the option runs until it terminates.

    **Goal-conditioned policies** are a related idea: train a policy $\pi(a | s, g)$ that can achieve any goal $g$, and then use a high-level policy to sequence goals. Hindsight Experience Replay (HER) (Andrychowicz et al., 2017; [arXiv:1707.01495](https://arxiv.org/abs/1707.01495)) makes goal-conditioned learning practical by relabeling failed trajectories with the goals they actually achieved.
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ---

    ## 6. Reward Shaping and Reward Hacking

    Defining the right reward function is one of the hardest problems in RL. Get it wrong, and the agent will find creative ways to exploit whatever signal you give it --- a phenomenon called **reward hacking** or **specification gaming**.

    Classic examples: a boat racing agent that finds it more rewarding to drive in circles collecting power-ups than to finish the race. A cleaning robot that covers its camera sensor so it can't "see" any mess. A simulated creature that learns to be very tall (maximizing its center of mass) by jittering in place rather than actually walking.

    **Reward shaping** --- adding intermediate rewards to guide learning --- can help, but it can also introduce new failure modes. The key theoretical result is the **potential-based shaping theorem** (Ng et al., 1999): if your shaping reward has the form $F(s, s') = \gamma \Phi(s') - \Phi(s)$ for some potential function $\Phi$, it preserves the optimal policy. Any other form of shaping can change the optimal policy arbitrarily.

    This connects to one of the deepest open problems in AI safety: how do you specify what you actually want?
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ---

    ## 7. Sim-to-Real Transfer

    Training in simulation is cheap and safe. Real robots are expensive and fragile. But policies trained in simulation often fail in the real world because the simulation is never perfectly accurate --- a problem called the **reality gap**.

    **Domain randomization** addresses this by randomizing the simulation's physical parameters (friction, mass, lighting, sensor noise) during training. If the policy learns to succeed across a wide range of simulated conditions, it's more likely to transfer to the real world, which is just one more "condition" in the distribution. OpenAI's Rubik's cube hand ([arXiv:1910.07113](https://arxiv.org/abs/1910.07113)) is a landmark demonstration.

    **System identification** takes the opposite approach: measure the real-world parameters carefully and make the simulation as accurate as possible. In practice, the best results often combine both strategies.
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ---

    ## 8. RL for Large Language Models

    Perhaps the most impactful application of RL in recent years is training language models to be helpful and safe. **Reinforcement Learning from Human Feedback (RLHF)** (Ouyang et al., 2022; [arXiv:2203.02155](https://arxiv.org/abs/2203.02155)) works in three stages:

    1. **Supervised fine-tuning** on high-quality demonstrations
    2. **Reward model training** --- a model that predicts human preferences between pairs of outputs
    3. **RL fine-tuning** --- optimize the language model against the reward model using PPO, with a KL penalty to prevent the model from drifting too far from the supervised baseline

    The KL penalty is crucial: without it, the model exploits the reward model (reward hacking again), producing outputs that score highly but are nonsensical to humans.

    **Constitutional AI** (Bai et al., 2022; [arXiv:2212.08073](https://arxiv.org/abs/2212.08073)) reduces reliance on human labelers by having the AI critique and revise its own outputs according to a set of principles, then training on the resulting preference data (RLAIF).

    **Process reward models** (Lightman et al., 2023; [arXiv:2305.20050](https://arxiv.org/abs/2305.20050)) provide feedback on each step of reasoning rather than just the final answer. This is critical for mathematical reasoning, where a correct final answer doesn't mean the reasoning was sound, and where step-level feedback dramatically improves performance.
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ---

    ## Recommended Resources

    **Textbooks and courses:**
    - [Sutton & Barto --- Reinforcement Learning: An Introduction](file:///C:/Users/landa/ml-course/textbooks/Sutton-RL.pdf) (complete the full book, especially Part II and III)
    - David Silver's RL Course (UCL, 2015) --- 10 lectures, freely on YouTube
    - OpenAI Spinning Up --- implementation-focused, excellent for building intuition through code
    - Sergey Levine's CS 285 (UC Berkeley) --- the most thorough advanced RL course available, lectures on YouTube

    **Key papers (in rough chronological order):**
    - Mnih et al., 2015 --- DQN ([arXiv:1312.5602](https://arxiv.org/abs/1312.5602))
    - Schulman et al., 2015 --- TRPO ([arXiv:1502.05477](https://arxiv.org/abs/1502.05477))
    - Silver et al., 2016 --- AlphaGo ([arXiv:1607.02239](https://arxiv.org/abs/1607.02239))
    - Schulman et al., 2017 --- PPO ([arXiv:1707.06347](https://arxiv.org/abs/1707.06347))
    - Silver et al., 2017 --- AlphaZero ([arXiv:1712.01815](https://arxiv.org/abs/1712.01815))
    - Haarnoja et al., 2018 --- SAC ([arXiv:1801.01290](https://arxiv.org/abs/1801.01290))
    - Schrittwieser et al., 2020 --- MuZero ([arXiv:1911.08265](https://arxiv.org/abs/1911.08265))
    - Hafner et al., 2020 --- Dreamer ([arXiv:1912.01603](https://arxiv.org/abs/1912.01603))
    - Kumar et al., 2020 --- CQL ([arXiv:2006.04779](https://arxiv.org/abs/2006.04779))
    - Chen et al., 2021 --- Decision Transformer ([arXiv:2106.01345](https://arxiv.org/abs/2106.01345))
    - Ouyang et al., 2022 --- InstructGPT/RLHF ([arXiv:2203.02155](https://arxiv.org/abs/2203.02155))
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ---

    ## Project Ideas

    1. **Implement PPO from scratch.** Don't use a library --- write the clipped objective, the GAE advantage estimator, the minibatch updates, and the value function baseline yourself. Train it on a continuous control task from Gymnasium (MuJoCo or the newer `gymnasium-robotics` environments). This is the single most valuable exercise for understanding modern RL.

    2. **Train an Atari agent with DQN and extensions.** Start with vanilla DQN, then add prioritized experience replay, double DQN, and dueling networks one at a time. Measure how each improvement affects learning speed and final performance. Use the ALE (Arcade Learning Environment) through Gymnasium.

    3. **Explore RLHF on a small language model.** Use the TRL (Transformer Reinforcement Learning) library from Hugging Face to fine-tune a small model (GPT-2 scale) with a reward model trained on preference data. Observe the reward hacking phenomenon firsthand by removing the KL penalty and watching the outputs degrade.

    4. **Build a simple model-based agent.** Learn a dynamics model from environment interactions and use it for planning (Dyna-style). Compare sample efficiency against a model-free baseline on the same task. Observe how model errors affect planning quality.

    5. **Self-play for a board game.** Implement AlphaZero-style self-play for Connect Four or Othello. Train a small neural network to predict move probabilities and game outcome, and use MCTS for move selection during self-play. Watch the agent discover strategies you didn't program.
    """)
    return


if __name__ == "__main__":
    app.run()
